a. Dla każdego departamentu wyświetl liczbę zatrudnionych w nim pracowników i ich średnią z ich minimalnego wynagrodzenia.
/* v1
SELECT DISTINCT EMP.DEPARTMENT_ID, COUNT(*) FROM EMPLOYEES EMP GROUP BY EMP.DEPARTMENT_ID ORDER BY EMP.DEPARTMENT_ID;
*/
/* v2
SELECT DISTINCT EMP.DEPARTMENT_ID, COUNT(*) as Liczba_pracownikow, AVG(J.MIN_SALARY)
FROM EMPLOYEES EMP, JOBS J
WHERE EMP.JOB_ID = J.JOB_ID
GROUP BY EMP.DEPARTMENT_ID 
ORDER BY EMP.DEPARTMENT_ID;

LUB BEZ WARUNKU "WHERE..."
*/
/* v3
SELECT DEP.DEPARTMENT_ID, COUNT(EMP.EMPLOYEE_ID), AVG(J.MIN_SALARY)
FROM DEPARTMENTS DEP LEFT JOIN EMPLOYEES EMP
ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID
LEFT JOIN JOBS J ON EMP.JOB_ID = J.JOB_ID
GROUP BY (DEP.DEPARTMENT_ID)
ORDER BY DEP.DEPARTMENT_ID;
*/
b. Dla każdego pracownika wyświetl jego kategorię płacową i widełki płacowe w jakich mieści się pensja pracownika.
/* v1
SELECT EMP.FIRST_NAME, EMP.LAST_NAME,J.JOB_TITLE, EMP.SALARY,J.MIN_SALARY, J.MAX_SALARY
FROM EMPLOYEES EMP, JOBS J
WHERE EMP.JOB_ID = J.JOB_ID;
*/
/* v2
SELECT EMP.FIRST_NAME, EMP.LAST_NAME,J.JOB_TITLE, EMP.SALARY,J.MIN_SALARY, 
J.MAX_SALARY, J2.JOB_TITLE AS STANOWISKO, 
J2.MIN_SALARY AS PLACA_MIN, J2.MAX_SALARY AS PLACA_MAX
FROM EMPLOYEES EMP, JOBS J, JOBS J2
WHERE EMP.JOB_ID = J.JOB_ID AND EMP.SALARY BETWEEN J2.MIN_SALARY AND J2.MAX_SALARY
ORDER BY EMP.LAST_NAME;
*/
c. Dla każdego pracownika posiadającego podwładnych wyświetl ich liczbę. Wyniki posortuj zgodnie z malejącą liczbą podwładnych.
/* v1
SELECT EMP2.FIRST_NAME, EMP2.LAST_NAME, EMP2.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.LAST_NAME, EMP.EMPLOYEE_ID, EMP.MANAGER_ID
FROM EMPLOYEES EMP
JOIN EMPLOYEES EMP2 ON EMP2.EMPLOYEE_ID=EMP.MANAGER_ID;
*/
/* v2
SELECT EMP.FIRST_NAME, EMP.LAST_NAME, EMP.EMPLOYEE_ID, COUNT(*) AS ILOSC_PODWLADNYCH
FROM EMPLOYEES EMP2
JOIN EMPLOYEES EMP ON EMP.EMPLOYEE_ID=EMP2.MANAGER_ID
GROUP BY EMP.FIRST_NAME, EMP.LAST_NAME, EMP.EMPLOYEE_ID
ORDER BY COUNT(*) DESC;
*/
d. Wyświetl numer departamentu, który nie zatrudnia żadnych pracowników.
/* v1
SELECT DISTINCT DEP.DEPARTMENT_ID
FROM DEPARTMENTS DEP
WHERE DEP.MANAGER_ID IS NULL
ORDER BY DEP.DEPARTMENT_ID ASC;
*/
/* v2
*/
e. Wyświetl dla każdego roku liczbę zatrudnionych w nim pracowników. Wynik uporządkuj zgodnie z liczbą zatrudnionych.
/* v1
SELECT EXTRACT(YEAR FROM EMP.HIRE_DATE) 
FROM EMPLOYEES EMP;
*/
/* v2
SELECT DISTINCT EXTRACT(YEAR FROM EMP.HIRE_DATE) AS HIRE_YEAR
FROM EMPLOYEES EMP
ORDER BY HIRE_YEAR DESC;
*/
/* v3 
SELECT EMP.FIRST_NAME, EMP.LAST_NAME, EMP.EMPLOYEE_ID, COUNT(*) AS ILOSC_PODWLADNYCH,
SUM(EMP2.SALARY) AS SUMA_WYNAGRODZ, AVG(EMP2.SALARY) AS SR_WYNAGRODZ,
SUM(EMP2.SALARY)/COUNT(*) AS SR
FROM EMPLOYEES EMP2
JOIN EMPLOYEES EMP ON EMP.EMPLOYEE_ID=EMP2.MANAGER_ID
GROUP BY EMP.FIRST_NAME, EMP.LAST_NAME, EMP.EMPLOYEE_ID
ORDER BY COUNT(*) DESC;
*/

https://stackoverflow.com/questions/30907374/how-to-get-number-of-employees-per-year
f. Wyświetl id departamentu, nazwę departamentu, nazwisko, wynagrodzenie, dla tych pracowników, którzy zarabiają mniej niż średnia płaca dla ich etatu.
