cw3 - cz1
1.
/*V1
SELECT PROD_SUBCATEGORY,PROD_SUBCATEGORY_ID, COUNT(*),
RANK() OVER(ORDER BY COUNT(*) DESC) RANKING
FROM H_PRODUCTS
GROUP BY (PROD_SUBCATEGORY,PROD_SUBCATEGORY_ID);
*/
2.
/*V1
SELECT PROD_SUBCATEGORY,PROD_SUBCATEGORY_ID, COUNT(*),
DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) RANKING
FROM H_PRODUCTS
GROUP BY (PROD_SUBCATEGORY,PROD_SUBCATEGORY_ID);
*/
3.
/*V1

*/
4.
5.
6.
7.
8.
